### ISSUE TITLE
Null Pointer Exception in ReceiveMessageThread

### ISSUE THREAD

**Issue by rbaid** [samarth-math/project-connect#4]
While transferring file received this error message: 

Exception in thread "ReceiveMessageThread" java.lang.NullPointerException
       at serverclient.ReceiveMessage.run(ReceiveMessage.java:41)
       at java.lang.Thread.run(Thread.java:745)

**Comment by samarth-math** [comment]
Will need to see code

**Comment by rajatvyas** [comment]
did it crash?

On Wed, May 20, 2015 at 9:40 PM, Sam <notifications@github.com> wrote:

> Will need to see code
>
> On 20 May 2015 21:36, "rbaid" <notifications@github.com> wrote:
>
> > While transferring file received this error message:
> >
> > Exception in thread "ReceiveMessageThread" java.lang.NullPointerException
> > at serverclient.ReceiveMessage.run(ReceiveMessage.java:41)
> > at java.lang.Thread.run(Thread.java:745)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/samarth-math/project-connect/issues/4>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/samarth-math/project-connect/issues/4#issuecomment-103942964>
> .
>



-- 
Rajat Vyas
Computer Science Graduate
LNM IIT, Jaipur

**Comment by rbaid** [comment]
No, the application as such didn't crash. But on command line there was
this exception and file transfer stopped, but there was no message that
file transfer stopped.

**Comment by samarth-math** [comment]
This one might be a lil tough to figure..!

Let's start getting into it.
