### ISSUE TITLE
IO Exception while writing log files, Multiple issues coming due to this exception

### ISSUE THREAD

**Issue by rbaid** [samarth-math/project-connect#5]
From the console following exception can be observed:

java.io.IOException: The system cannot find the path specified
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(Unknown Source)
        at LogMaintainence.ChatLogging.writeLogToFile(ChatLogging.java:171)
        at LogMaintainence.ChatLogging.run(ChatLogging.java:121)
        at java.lang.Thread.run(Unknown Source)

**Comment by samarth-math** [comment]
Right, I'm guessing you just downloaded the repo right?
you need to download and link the JSON library.

I've attached it, just remove the .zip from the end, and go to 
Build Path> Configure Build Path > Java Build Path > Libraries

And add the library!

**Comment by samarth-math** [comment]
Previous comment was wrong.
This can be fixed by changing the base path of the file, which is written without using the os.pathSeparator I believe.
